include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # === Dart Best Practices ===
    avoid_print: true
    prefer_final_locals: true
    prefer_final_fields: true
    avoid_unused_constructor_parameters: true
    unnecessary_this: true
    always_declare_return_types: true
    omit_local_variable_types: false
    prefer_typing_uninitialized_variables: true

    # === Code Style Improvements ===
    prefer_single_quotes: true
    unnecessary_string_interpolations: true
    avoid_redundant_argument_values: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_constructors_in_immutables: true

    # === Safety / Null-safety ===
    always_require_non_null_named_parameters: true
    null_check_on_nullable_type_parameter: true

    # === Performance ===
    unnecessary_await_in_return: true
    use_string_buffers: true

    # === Flutter Specific Good Practices ===
    use_key_in_widget_constructors: true
    sized_box_for_whitespace: true
    avoid_unnecessary_containers: true

    # === Readability ===
    prefer_interpolation_to_compose_strings: true
    use_enums: true
    file_names: true